[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
inference_staking = "7NuTZJFDezrh8n73HxY22gvPrXnGeRqDAoFDnXHnMjQb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/inference-staking.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/rewards.ts"
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/constraints.ts"
