[features]
resolution = true
skip-lint = false

[programs.localnet]
inference_staking = "stkxmBvNyGRH6FWi4tjFtPpL9XmwnT9ZpqrQnUogvHG"

[programs.devnet]
inference_staking = "stkxmBvNyGRH6FWi4tjFtPpL9XmwnT9ZpqrQnUogvHG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "keys/devnet/deployer-keypair.json"

[scripts]
test = "bun run ts-mocha -p ./tsconfig.json -r tsconfig-paths/register -t 100000000 tests/**/multi-epochs.test.ts"
# test = "bun run ts-mocha -p ./tsconfig.json -r tsconfig-paths/register -t 1000000 tests/**/inference-staking.test.ts"
# test = "bun run ts-mocha -p ./tsconfig.json -r tsconfig-paths/register -t 1000000 tests/**/rewards.test.ts"
# test = "bun run ts-mocha -p ./tsconfig.json -r tsconfig-paths/register -t 1000000 tests/**/constraints.test.ts"
